### ISSUE TITLE
Add arm8l support

### ISSUE THREAD

**Issue by l4cr0ss** [bannsec/revenge#3]
This might be as simple as adding it to  `uname_standard` in `./revenge/devices/__init__.py`. 

What do you think?

**Comment by bannsec** [comment]
So it'll have to be added there, a CPUContext will need to be created for it, and i think there are a few other places that will need to. Since some recent restructuring this should be easier actually. I'll take a look at it.

**Comment by bannsec** [comment]
Added the CPUContext to master. It loads on my arm api24 emulator. Let me know if you have issues running it on your device.

**Comment by l4cr0ss** [comment]
Gonna do my best to get this tested on a few different arm devices this week and confirm that piece.

**Comment by l4cr0ss** [comment]
According to its packaging, this phone I have is supposed to have an ARM 8 abi. Well it turns out it doesn't really have an ARM 8 abi! I was able to also confirm that stuff appears working correctly on Arm 7. Thank you.
